//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections;
using UnityEngine;
using UnityEngine.UI;

namespace AssemblyCSharp
{
	public class selectTechNotify : MonoBehaviour
	{
		public Text nextButtonText;
		public Button traitButton;
		public selectTechNotify ()
		{
		}

		void Start () {
		}

		void Update () {
			if (!Global.players [Global.currentPlayer].TechSelected) {
				nextButtonText.text = "Select Trait!";
				traitButton.image.color = Color.red;
			} else {
				nextButtonText.text = "Next Turn";
				traitButton.image.color = Color.white;
			}
		}
	}
}

