// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public static class Formula
	{
		public static double GrowthRate(int level) {
			return ((double) level) * 0.1;
		}

		public static int GrowthCap(int level) {
			return Global.baseCapacity * level * 10;
		}

		public static int LosePop(Player Player1, Player PlayerX, int Pop1, int PopX) {
			return (int)(((double)(Player1.getDefenseValue() - PlayerX.getAttackValue())/
			              (double)(Player1.getAttackValue() + PlayerX.getAttackValue() + Player1.getDefenseValue() + PlayerX.getDefenseValue()) - 0.05) * (double)(Pop1 * PopX));
		}

		public static int GainPop(Player Player1, Player PlayerX, int Pop1, int PopX) {
			return (int)(((double)(Player1.getAttackValue() - PlayerX.getDefenseValue())/
			        (double)(Player1.getAttackValue() + PlayerX.getAttackValue() + Player1.getDefenseValue() + PlayerX.getDefenseValue()) + 0.05) * (double)(Pop1 * PopX));
		}

		public static double spreadThreshold(int level) {
			if (level < 0)
				return 0.9;
			if (level > 6)
				return 0.3;
			else
				return 0.9 - ((double) level) * 0.1;
		}

	}
}

