//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

using System.Collections.Generic;
using Gamelogic.Grids;
namespace AssemblyCSharp
{
	public class Global
	{	public readonly static int Growth =0;
		public readonly static int Exploration=1;
		public readonly static int Attacking=2;
		public readonly static int Defensive = 3;
		public readonly static int Ultimate = 4;

		public static int[][] techCost;
		public static DiamondGrid<SpriteCell> grid;
		public static Dictionary<DiamondPoint ,int> pops;
		public static int numTurns = 0;
		public static int currentPlayer;
		public static List<Player> players = new List<Player>();
		public static List<Cell> cells = new List<Cell>();
		public static Player winner;
		public static Player firstPlayer;
		public static Demo demo;
		public Global ()
		{
		}


		public static void updateDemo(){
		}

		public static void updateWinStatus(){
		}
	}
}

