//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class Player
	{
		private int netPop = 0;
		private int numCell = 0;
		//whether tech get Upgrade last turn
		private bool techUp = false;
		//techAndProgree[Global.Techs.Exploration][0] the level techAndProgree[Global.Techs.Exploration][1] progress
		private int[,] techAndProgress;
		private int techOnResearch;
		public Player ()
		{
			techAndProgress = new int[5,2];
		}

		public void update(){
			netPop = 0;
			numCell = 0;

			System.Collections.IEnumerator en = Global.grid.GetEnumerator();

			foreach (Cell cell in en) {
				int tmpPop = cell.getPop(this);
				if(tmpPop != 0) numCell++;
				netPop += tmpPop;
			}
		}
	}
}

